### ISSUE TITLE
panic: 184:439 (8671): rule QuotedBody: interface conversion: interface {} is string, not []uint8

### ISSUE THREAD

**Issue by andrewarrow** [soapywu/pbxproj#3]
tried the example with just a simple `project.pbxproj` from a brand new simple ios app from xcode wizard but got:

panic: 184:439 (8671): rule QuotedBody: interface conversion: interface {} is string, not []uint8

**Comment by soapywu** [comment]
> tried the example with just a simple `project.pbxproj` from a brand new simple ios app from xcode wizard but got:
> 
> panic: 184:439 (8671): rule QuotedBody: interface conversion: interface {} is string, not []uint8

The parser did not handle the contents which contained escaped quote(\\") correctly, I have fixed it. 

BTW, this project was not fully tested, and may be *UNMAINTAINED*,  use it at your own risk.
